### ISSUE TITLE
Game crashes at random with CPUs in Offline mode

### ISSUE THREAD

**Issue by Kemuja** [puyonexus/puyovs#47] opened 2023-11-22 16:00 UTC
I know, it's CPUs only, because this never happened with solo offline nor with other players online.

Due to it seemingly happening at random, it's hard to know, what causes it. (Version B31)

**Comment by dec32nd** [comment] 2024-02-12 03:18
Duplicate of #8

**Closed by dec32nd** 2024-02-12 03:18 UTC
